# Nome da ação para identificação
name: Add Definition of Done to Issue Description

# Evento que dispara a ação: criação de uma nova issue
on:
  issues:
    types: [opened]

# Definição dos jobs a serem executados
jobs:
  update-description:
    # Ambiente onde a ação será executada: Ubuntu (Linux)
    runs-on: ubuntu-latest

    steps:
    - name: Set description text
      run: |
        # Texto da Definição de Pronto (Definition of Done) que será adicionado à issue
        TEXT_TO_ADD="**Definição de Pronto**: \n- Código revisado \n- Testes implementados \n- Documentação atualizada"

        # Número da issue que acabou de ser criada, extraído do evento
        ISSUE_NUMBER="${{ github.event.issue.number }}"

        # Nome do repositório onde a issue foi criada
        REPO_NAME="${{ github.repository }}"

        # Comando para pegar a descrição atual da issue
        CURRENT_DESCRIPTION=$(gh issue view $ISSUE_NUMBER --repo $REPO_NAME --json body --jq ".body")

        # Combina a descrição atual da issue com a Definição de Pronto
        UPDATED_DESCRIPTION="$CURRENT_DESCRIPTION\n\n$TEXT_TO_ADD"

        # Atualiza a descrição da issue com o texto combinado
        gh issue edit $ISSUE_NUMBER --body "$UPDATED_DESCRIPTION" --repo $REPO_NAME

    # Variável de ambiente para autenticar a ação no GitHub
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
